[package]
name = "atelier-core"
version = "0.1.0"
edition = "2018"

[features]
serde-1 = ["serde"]
asset_uuid_macro = ["asset-uuid"]

[dependencies]
uuid = { version = "0.8", features = [ "v4" ] }
asset-uuid = { path = "./asset-uuid", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
futures-core = { version = "0.3", default-features = false }

[dev-dependencies]
serde_json = "1.0"
bincode = "1.3"
