[package]
name = "atelier-daemon"
version = "0.1.0"
edition = "2018"

[dependencies]
atelier-core = { path = "../core" }
atelier-schema = { path = "../schema" }
atelier-importer = { path = "../importer" }
atelier-loader = { path = "../loader" }
dunce = "1.0"
path-clean = "0.1"
path-slash = "0.1.1"
capnp = { version = "0.13", features = ["unaligned"] }
capnp-rpc = "0.13"
notify = "4.0.0"
lmdb-rkv = "0.14"
rayon = { version = "1.3", optional = true }
log = { version = "0.4", features = ["serde"] }
tokio = { version = "0.2", features = ["tcp", "fs", "sync", "time", "rt-core", "rt-util", "stream", "rt-threaded"] }
tokio-util = { version = "0.3", features = ["compat"] }
futures = { version = "0.3", default-features = false, features = ["std", "async-await", "executor"] }
futures-util = { version = "0.3", default-features = false }
futures-core = { version = "0.3", default-features = false }
futures-io = { version = "0.3", default-features = false }
futures-executor = { version = "0.3", default-features = false }
futures-channel = { version = "0.3", default-features = false }
async-lock = { version = "2.1" }
async-channel = { version = "1.4" }
event-listener = { version = "2.4.0" }
mopa = "0.2"
serde = "1.0"
serde_derive = "1.0"
erased-serde = "0.3"
bincode = "1.3"
ron = "0.5"
num_cpus = "1.10"
smush = { version = "0.1", default-features = false, features = [ "lz4_support" ], optional = true }
fern = { version = "0.5", optional = true }
chrono = { version = "0.4", default-features = false, optional = true }
pin-project = "0.4.8"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
tempfile = "3"

[features]
compression = [ "smush" ]
parallel_hash = [ "rayon" ]
pretty_log = [ "chrono", "fern" ]
serde_importers = []
"atelier_importer/serde_importers" = ["serde_importers"]