[package]
name = "atelier-importer"
version = "0.1.0"
edition = "2018"

[dependencies]
atelier-core = { path = "../core", features = ["serde-1"] }
uuid = { version = "0.8", features = ["v4"] }
mopa = "0.2"
serde = "1.0"
type-uuid = "0.1"
erased-serde = "0.3"
ron = { version = "0.5", optional = true }
typetag = { version = "0.1", optional = true }
serde-importable-derive = { path = "./serde-importable-derive", optional = true }
futures-io = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false }
futures-core = { version = "0.3", default-features = false }
log = { version = "0.4", features = ["serde"] }

[features]
serde_importers = ["typetag", "serde-importable-derive", "ron"]